version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mi_postgres
    restart: always
    environment:
      POSTGRES_USER: default_user  # Será reemplazado por Vault
      POSTGRES_PASSWORD: default_pass  # Será reemplazado por Vault
      POSTGRES_DB: mi_base_datos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - vault

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://0.0.0.0:8200"
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data

  setup:
    image: python:3.9
    container_name: setup_vault
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres
      - vault
    entrypoint:
      - "sh"
      - "-c"
      - |
        pip install --no-cache-dir --upgrade pip &&
        pip install --no-cache-dir requests python-dotenv &&
        python setup_vault.py

volumes:
  postgres_data:
  vault_data:
