version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.ssl
    container_name: mi_postgres
    restart: always
    environment:
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: default_pass
      POSTGRES_DB: mi_base_datos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - "postgres"
      - "-c"
      - "ssl=on"
      - "-c"
      - "ssl_cert_file=/var/lib/postgresql/server.crt"
      - "-c"
      - "ssl_key_file=/var/lib/postgresql/server.key"

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: http://0.0.0.0:8200
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data

  setup:
    image: python:3.9
    container_name: setup_vault
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres
      - vault
    entrypoint:
      - "sh"
      - "-c"
      - |
        pip install --no-cache-dir --upgrade pip &&
        pip install --no-cache-dir requests python-dotenv &&
        python setup_vault.py

volumes:
  postgres_data:
  vault_data:
