FROM postgres:15

RUN apt-get update && \
    apt-get install -y postgresql-15-pgaudit && \
    rm -rf /var/lib/apt/lists/*

COPY certs_pgsql/server.crt /var/lib/postgresql/server.crt
COPY certs_pgsql/server.key /var/lib/postgresql/server.key
RUN chmod 600 /var/lib/postgresql/server.key
RUN chown postgres:postgres /var/lib/postgresql/server.key


